apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-keyvault
    kind: SecretStore
  target:
    name: secret-sample
    creationPolicy: Owner
  data:
    - secretKey: creds
      remoteRef:
        key: secret/Bernardo
  # dataFrom:
  #   - extract:
  #       key: Bernardo
