apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-keyvault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: "495a6f2f-e021-4750-b745-9b4282842206"
      vaultUrl: "https://akv-secrets.vault.azure.net/"
      authSecretRef:
        clientId:
          name: secret-eso-keyvault-sp
          key: ClientID
        clientSecret:
          name: secret-eso-keyvault-sp
          key: ClientSecret
